# Generated by Django 5.1.3 on 2024-11-18 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('version_number', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100, unique=True)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('s3_key', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=False)),
                ('uploaded_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'FileVersion',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100, unique=True)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('s3_key', models.CharField(max_length=150)),
                ('current_version', models.IntegerField()),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
