# Generated by Django 5.1.3 on 2024-11-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='owner_id',
        ),
        migrations.DeleteModel(
            name='FileVersion',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
