# Generated by Django 5.1.3 on 2024-11-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='fileversion',
            old_name='file_id',
            new_name='file',
        ),
    ]
